# Generated by Django 2.2.4 on 2021-05-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outhor',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
